# Generated by Django 5.0 on 2024-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='final_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='round_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='round_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='technical_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephonic_round',
            field=models.BooleanField(default=False),
        ),
    ]
