# Generated by Django 5.0 on 2024-04-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_final_round_employee_hr_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='married_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Unmarried', max_length=100),
        ),
    ]
