# Generated by Django 4.2.6 on 2024-05-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0047_announcement_policies_alter_candidateresume_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_alter_department_name_alter_designation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(default='Select Designations', on_delete=django.db.models.deletion.PROTECT, related_name='designation', to='employee.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.candidateresume'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.designation', verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='documents_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hr.onboarding'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emp_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.position', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.work_office', verbose_name='work_office'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='resignapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
