# Generated by Django 4.2.6 on 2024-05-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0072_alter_candidateresume_resume'),
        ('employee', '0007_employee_company_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_office',
        ),
        migrations.AddField(
            model_name='employee',
            name='WeekOff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.weekoff'),
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.holidaymaster'),
        ),
    ]
