# Generated by Django 4.2.6 on 2024-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_department_name_alter_designation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contactname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contactnumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_relationas',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], default='Not Update', max_length=100),
        ),
    ]
