# Generated by Django 4.2.6 on 2024-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_emergency_contactname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='regularization_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='requested_clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='requested_clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
