# Generated by Django 4.2.6 on 2024-06-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_attendance_regularization_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
