# Generated by Django 4.2.6 on 2024-08-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_attendance_latitude_attendance_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='esic_apply',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='final_round',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hr_round',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='interview_take',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permission_all',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permission_customize',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_apply',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='round_three',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='round_two',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='technical_round',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='telephonic_round',
        ),
    ]
