# Generated by Django 5.0 on 2024-03-01 10:59

import django.db.models.deletion
import django.utils.timezone
import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateResume',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to=hr.models.resume_upload_path)),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Close', 'Close'), ('On hold', 'On hold')], default='-------', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Exp', models.FloatField(null=True)),
                ('interviewFeedback', models.CharField(choices=[('Pending', 'Pending'), ('On-Hold', 'On-Hold'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='department')),
                ('designation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.designation', verbose_name='designation')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewMode', models.CharField(choices=[('', 'Select'), ('Online', 'Online'), ('Face to Face', 'Face to Face')], max_length=20)),
                ('interviewer', models.CharField(max_length=255)),
                ('interviewRound', models.CharField(choices=[('', 'Select'), ('Telephonic Round', 'Telephonic Round'), ('HR Round', 'HR Round'), ('Technical Round', 'Technical Round'), ('Round Two', 'Round Two'), ('Round Three', 'Round Three'), ('Final Round', 'Final Round')], max_length=20)),
                ('interviewDate', models.DateField()),
                ('interviewTime', models.TimeField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateresume')),
            ],
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_psimg', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_adhar', models.FileField(upload_to='resume_upload_path')),
                ('c_pan', models.FileField(upload_to='resume_upload_path')),
                ('c_bankDetails', models.FileField(upload_to='resume_upload_path')),
                ('c_bankStatement', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_salarySlips', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_expLetter', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_previousJoiningLetter', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_degree', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_masters', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_HSC', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_SSC', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_otherCertificate', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateresume')),
            ],
        ),
    ]
