# Generated by Django 4.2.6 on 2024-08-05 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateResume',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to=hr.models.resume_upload_path)),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Close', 'Close'), ('On hold', 'On hold')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Exp', models.FloatField(null=True)),
                ('interviewFeedback', models.CharField(choices=[('Pending', 'Pending'), ('On-Hold', 'On-Hold'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('IsEmployeeNow', 'IsEmployeeNow')], default='Pending', max_length=20)),
                ('interviewFeedback_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department', verbose_name='department')),
                ('designation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.designation', verbose_name='designation')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('industries_type', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo_upload_path')),
                ('reg_address', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_city', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_state', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_country', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_pin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_address', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_city', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_state', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_country', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_pin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=15, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=25, null=True)),
                ('pancard_no', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaarcard_no', models.CharField(blank=True, max_length=20, null=True)),
                ('account_no', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='company_document_upload_path')),
                ('emp_id_series', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeekOffNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', max_length=2)),
                ('weekoff', models.ForeignKey(default='Select Weekoff_nos', on_delete=django.db.models.deletion.PROTECT, related_name='weekoff_nos', to='hr.weekoff', verbose_name='Week Off')),
            ],
        ),
        migrations.CreateModel(
            name='WeekOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, max_length=10)),
                ('week_value', models.CharField(choices=[(0, 'Half Day'), (1, 'Full Day'), (2, 'Off')], default=0, max_length=10)),
                ('week_no', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='weekoff_day', to='hr.weekoffno', verbose_name='Week No')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(max_length=10)),
                ('remarks', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='company_Policies_upload_path')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_policy', to='hr.company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_psimg', models.FileField(default='/resume_upload_path/avtar.jpg', upload_to='resume_upload_path')),
                ('c_adhar', models.FileField(upload_to='resume_upload_path')),
                ('c_pan', models.FileField(upload_to='resume_upload_path')),
                ('c_bankDetails', models.FileField(upload_to='resume_upload_path')),
                ('c_bankStatement', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_salarySlips', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_expLetter', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_previousJoiningLetter', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_degree', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_masters', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_HSC', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_SSC', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('c_otherCertificate', models.FileField(blank=True, null=True, upload_to='resume_upload_path')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('kyc_complete', 'KYC Complete')], default='pending', max_length=20)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.candidateresume')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewMode', models.CharField(choices=[('', 'Select'), ('Online', 'Online'), ('Face to Face', 'Face to Face')], max_length=20)),
                ('interviewer', models.CharField(max_length=255)),
                ('interviewRound', models.CharField(choices=[('HR Round', 'HR Round'), ('Technical Round', 'Technical Round'), ('Managerial Round', 'Managerial Round')], max_length=20)),
                ('interviewDate', models.DateField()),
                ('interviewTime', models.TimeField()),
                ('interviewround_remarks', models.CharField(max_length=255)),
                ('interviewround_status', models.IntegerField(choices=[(1, 'Complete'), (2, 'Pending'), (3, 'Rejected')], default=2)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.candidateresume')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department', verbose_name='Department')),
                ('designation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.designation', verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('festival_name', models.CharField(max_length=100)),
                ('holiday_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.holidaymaster')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayrollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ca', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sa', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pt', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employer_pf', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employer_esic', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employee_pf', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employee_esic', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('company', models.ForeignKey(default='Select Company Payroll', on_delete=django.db.models.deletion.PROTECT, related_name='company_payroll', to='hr.company', verbose_name='CompanyPayrollDetails')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pin_code', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, max_length=10, null=True)),
                ('end_date', models.DateField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('company', models.ForeignKey(default='Select Company Branch', on_delete=django.db.models.deletion.PROTECT, related_name='company_branch', to='hr.company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('ifsc_code', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('account_no', models.DecimalField(decimal_places=0, max_digits=25)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('company', models.ForeignKey(default='Select Company Bank', on_delete=django.db.models.deletion.PROTECT, related_name='company_bank', to='hr.company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='company_Announcement_postupload_path')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_announcement', to='hr.company', verbose_name='company')),
            ],
        ),
    ]
