# Generated by Django 5.0 on 2024-03-14 11:03

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='interviewFeedback',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On-Hold', 'On-Hold'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('IsEmployeeNow', 'IsEmployeeNow')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
