# Generated by Django 5.0 on 2024-03-14 18:27

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
