# Generated by Django 5.0 on 2024-03-15 16:29

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_interview_interviewer_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewer_name',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
