# Generated by Django 5.0 on 2024-03-20 11:04

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_rename_interviewer_remarks_interview_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='remarks',
            new_name='interviewround_remarks',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
