# Generated by Django 5.0 on 2024-03-27 10:33

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_rename_remarks_interview_interviewround_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='interviewFeedback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewround_status',
            field=models.IntegerField(choices=[(1, 'Select'), (2, 'Pending'), (3, 'Rejected')], default=2),
        ),
    ]
