# Generated by Django 5.0 on 2024-03-27 15:23

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_alter_candidateresume_resume_alter_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('kyc_complete', 'KYC Complete')], default='pending', max_length=20),
        ),
    ]
