# Generated by Django 5.0 on 2024-03-27 15:30

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_alter_candidateresume_resume_alter_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
