# Generated by Django 4.2.6 on 2024-05-01 09:31

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.CreateModel(
            name='HolidayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('festival_name', models.CharField(max_length=100)),
                ('holiday_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.holidaymaster')),
            ],
        ),
    ]
