# Generated by Django 4.2.6 on 2024-05-02 12:39

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_holidaymaster_alter_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='holidaymaster',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
