# Generated by Django 4.2.6 on 2024-05-02 15:00

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_alter_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('website', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo_upload_path')),
                ('industries_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('gst_no', models.CharField(max_length=100)),
                ('tin_no', models.CharField(max_length=100)),
                ('pancard_no', models.CharField(max_length=20)),
                ('aadhaarcard_no', models.CharField(max_length=20)),
                ('account_no', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('company_start_date', models.CharField(max_length=100)),
                ('company_end_date', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='company_document_upload_path')),
            ],
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
