# Generated by Django 4.2.6 on 2024-05-02 15:08

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_start_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
