# Generated by Django 4.2.6 on 2024-05-02 15:31

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_rename_company_end_date_company_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cin_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
