# Generated by Django 4.2.6 on 2024-05-02 17:40

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pin_code', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tart_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True)),
                ('company', models.ForeignKey(default='Select Company Branch', on_delete=django.db.models.deletion.CASCADE, related_name='company_branch', to='hr.company', verbose_name='company')),
            ],
        ),
    ]
