# Generated by Django 4.2.6 on 2024-05-03 10:35

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0043_alter_candidateresume_resume_companybranch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='corp_address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='corp_city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='country',
            new_name='corp_country',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='pin_code',
            new_name='corp_pin_code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='state',
            new_name='corp_state',
        ),
        migrations.RenameField(
            model_name='companybranch',
            old_name='tart_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reg_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reg_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reg_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reg_pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reg_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
