# Generated by Django 4.2.6 on 2024-05-06 12:10

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_attendance_employee_and_more'),
        ('hr', '0047_announcement_policies_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekof_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
                ('remarks', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='company_Policies_upload_path')),
            ],
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='designation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.designation', verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='company',
            field=models.ForeignKey(default='Select Company Branch', on_delete=django.db.models.deletion.PROTECT, related_name='company_branch', to='hr.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.candidateresume'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.candidateresume'),
        ),
    ]
