# Generated by Django 4.2.6 on 2024-05-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0044_alter_candidateresume_resume'),
        ('hr', '0048_weekof_master_alter_candidateresume_department_and_more'),
    ]

    operations = [
    ]
