# Generated by Django 4.2.6 on 2024-05-08 11:25

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_merge_20240508_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeekOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, max_length=10)),
                ('week_value', models.CharField(choices=[(0, 'Full Day'), (1, 'Half Day'), (2, 'Off')], default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeekOffNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', max_length=2)),
                ('weekoff', models.ForeignKey(default='Select Weekoff_nos', on_delete=django.db.models.deletion.PROTECT, related_name='weekoff_nos', to='hr.weekoff', verbose_name='Week Off')),
            ],
        ),
        migrations.DeleteModel(
            name='Weekof_Master',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AddField(
            model_name='weekoffday',
            name='week_no',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='weekoff_day', to='hr.weekoffno', verbose_name='Week No'),
        ),
    ]
