# Generated by Django 4.2.6 on 2024-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_merge_20240508_0958'),
        ('hr', '0050_weekoff_weekoffday_weekoffno_delete_weekof_master_and_more'),
    ]

    operations = [
    ]
