# Generated by Django 4.2.6 on 2024-05-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_merge_20240508_1349'),
        ('hr', '0051_merge_20240508_1522'),
    ]

    operations = [
    ]
