# Generated by Django 4.2.6 on 2024-05-08 18:08

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_merge_20240508_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='weekoffday',
            name='week_value',
            field=models.CharField(choices=[(1, 'Full Day'), (2, 'Half Day'), (3, 'Off')], default=0, max_length=10),
        ),
    ]
