# Generated by Django 4.2.6 on 2024-05-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_alter_candidateresume_resume'),
        ('hr', '0052_merge_20240508_1558'),
    ]

    operations = [
    ]
