# Generated by Django 4.2.6 on 2024-05-09 10:05

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0053_alter_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='weekoffday',
            name='week_value',
            field=models.CharField(choices=[(0, 'Full Day'), (1, 'Half Day'), (2, 'Off')], default=0, max_length=10),
        ),
    ]
