# Generated by Django 4.2.6 on 2024-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0053_alter_candidateresume_resume_and_more'),
        ('hr', '0053_merge_20240509_0903'),
    ]

    operations = [
    ]
