# Generated by Django 4.2.6 on 2024-05-09 10:52

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0055_alter_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='weekoffday',
            name='week_no',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='weekoff_day', to='hr.weekoffno', verbose_name='Week No'),
        ),
    ]
