# Generated by Django 4.2.6 on 2024-05-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_merge_20240509_0943'),
        ('hr', '0056_alter_candidateresume_resume_and_more'),
    ]

    operations = [
    ]
