# Generated by Django 4.2.6 on 2024-05-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_alter_candidateresume_resume_alter_company_email_id'),
        ('hr', '0057_merge_20240509_1430'),
    ]

    operations = [
    ]
