# Generated by Django 4.2.6 on 2024-05-10 11:37

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0058_merge_20240510_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
