# Generated by Django 4.2.6 on 2024-05-10 11:41

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0060_alter_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='end_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='start_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='holidaymaster',
            name='year',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='policies',
            name='created_on',
            field=models.DateField(max_length=10),
        ),
    ]
