# Generated by Django 4.2.6 on 2024-05-10 15:05

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_alter_candidateresume_resume_alter_company_cin_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.CreateModel(
            name='CompanyBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('ifsc_code', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('account_no', models.DecimalField(decimal_places=0, max_digits=25)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(default='Select Company Bank', on_delete=django.db.models.deletion.PROTECT, related_name='company_bank', to='hr.company', verbose_name='company')),
            ],
        ),
    ]
