# Generated by Django 4.2.6 on 2024-05-10 17:26

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0064_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='company',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ifsc_code',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
