# Generated by Django 4.2.6 on 2024-05-13 16:58

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0065_remove_company_account_no_remove_company_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_announcement', to='hr.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policies',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_policy', to='hr.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='policies',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
