# Generated by Django 4.2.6 on 2024-05-16 17:43

from django.db import migrations, models
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0067_company_account_no_company_bank_name_company_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='end_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
