# Generated by Django 4.2.6 on 2024-05-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0068_alter_candidateresume_resume_alter_company_end_date'),
        ('hr', '0072_alter_candidateresume_resume'),
    ]

    operations = [
    ]
