# Generated by Django 4.2.6 on 2024-05-29 10:18

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0074_alter_candidateresume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewRound',
            field=models.CharField(choices=[('Telephonic Round', 'Telephonic Round'), ('HR Round', 'HR Round'), ('Technical Round', 'Technical Round'), ('Round Two', 'Round Two'), ('Round Three', 'Round Three'), ('Final Round', 'Final Round')], max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyPayrollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ca', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sa', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pt', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employer_pf', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employer_esic', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employee_pf', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('employee_esic', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('company', models.ForeignKey(default='Select Company Payroll', on_delete=django.db.models.deletion.PROTECT, related_name='company_payroll', to='hr.company', verbose_name='CompanyPayrollDetails')),
            ],
        ),
    ]
