# Generated by Django 4.2.6 on 2024-05-29 12:15

from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_work_office_employee_weekoff_and_more'),
        ('hr', '0075_alter_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='interview',
            name='designation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.designation', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to=hr.models.resume_upload_path),
        ),
    ]
