"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'# Set your desired time zone here
USE_I18N = True
USE_L10N = True
USE_TZ = False  # Ensure that USE_TZ is set to True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u-e+^4cie@g&49=%e7_8jn98(*egsmfb8j_$#lembb2s_)vdj#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = ['*']  # '*', '4992-2402-a00-152-642c-a078-6cb3-b69c-ac8e.ngrok-free.app'

# CSRF_TRUSTED_ORIGINS = ['https://4992-2402-a00-152-642c-a078-6cb3-b69c-ac8e.ngrok-free.app']

# CORS_ALLOWED_ORIGINS = [
#     'https://e02a-2402-a00-152-642c-a078-6cb3-b69c-ac8e.ngrok-free.app',
    # Add any other origins as needed
# ]

# Application definition


INSTALLED_APPS = [
    #MyApps
    'report',
    'payroll',
    'accounts',
    'core',
    'employee',
    'hr',

    #Default Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap_datepicker_plus',
    'tempus_dominus',
    'hr.management',
    'django_celery_beat',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'employee.context_processors.mycontext'
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'nvs_hr',         
#         'USER': 'admin',       
#         'PASSWORD': 'P@$$w0rd',    
#         'HOST': 'localhost',             
#         'PORT': '',              
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# Define the directories where static files are stored for each app.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# GOOGLE_OAUTH_CLIENT_SECRET_FILE = 'credentials.json'
# GOOGLE_OAUTH_REDIRECT_URI = 'https://4992-2402-a00-152-642c-a078-6cb3-b69c-ac8e.ngrok-free.app/hr/auth/callback'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # Set the desired logging level
    },
}


#SMTP Configuration

EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
#EMAIL_FILE_PATH = BASE_DIR/'emails'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'venilakaur@gmail.com'
EMAIL_HOST_PASSWORD = 'mchcyumegyjbvxrw'



# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Use the URL of your chosen message broker (e.g., Redis)

CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Use the URL of your chosen result backend

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'


from datetime import timedelta
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'scheduled_task': {
        'task': 'hr.models.scheduled_task',
        'schedule': crontab(hour=19, minute=00),
    },
}
