# Generated by Django 5.0 on 2024-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='remarks'),
        ),
    ]
