# Generated by Django 5.0 on 2024-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_salary',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
