# Generated by Django 4.2.6 on 2024-05-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_attendance_employee_and_more'),
        ('payroll', '0003_monthly_salary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
