# Generated by Django 4.2.6 on 2024-06-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_work_office_employee_weekoff_and_more'),
        ('payroll', '0004_alter_payroll_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salary',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
            preserve_default=False,
        ),
    ]
