# Generated by Django 4.2.6 on 2024-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_monthly_salary_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_netpayinwords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
