# Generated by Django 4.2.6 on 2024-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_monthly_salary_monthly_netpayinwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_incentive',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='incentive'),
        ),
    ]
