# Generated by Django 4.2.6 on 2024-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_monthly_salary_monthly_incentive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_basic',
            field=models.FloatField(default=0, verbose_name='monthly_basic'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_ca',
            field=models.FloatField(default=0, verbose_name='monthly_ca'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_ctc',
            field=models.FloatField(default=0, verbose_name='monthly_ctc'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_employeeesic',
            field=models.FloatField(default=0, verbose_name='monthly_employeeesic'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_employeepf',
            field=models.FloatField(default=0, verbose_name='monthly_employeepf'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_employeresic',
            field=models.FloatField(default=0, verbose_name='monthly_employeresic'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_employerpf',
            field=models.FloatField(default=0, verbose_name='monthly_employerpf'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_gross_salary',
            field=models.FloatField(default=0, verbose_name='monthly_gross_salary'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_hra',
            field=models.FloatField(default=0, verbose_name='monthly_hra'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_incentive',
            field=models.FloatField(default=0, verbose_name='incentive'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_loan_other',
            field=models.FloatField(default=0, verbose_name='monthly_loan_other'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_netpay',
            field=models.FloatField(default=0, verbose_name='monthly_netpay'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_newctc',
            field=models.FloatField(default=0, verbose_name='monthly_newctc'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_professionalTax',
            field=models.FloatField(default=0, verbose_name='monthly_professionalTax'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_sa',
            field=models.FloatField(default=0, verbose_name='monthly_sa'),
        ),
        migrations.AlterField(
            model_name='monthly_salary',
            name='monthly_total_deductions',
            field=models.FloatField(default=0, verbose_name='monthly_total_deductions'),
        ),
    ]
